2024-12-06 20:02:06,691:bot_manager.py:start_bot:20:INFO:Бот 5 успешно запущен
2024-12-06 20:14:12,442:bot_manager.py:start_bot:20:INFO:Бот 5 успешно запущен
2024-12-06 20:14:55,163:bot_manager.py:start_bot:20:INFO:Бот 1 успешно запущен
2024-12-06 20:15:09,139:bot_manager.py:start_bot:22:ERROR:Бот 5 не запущен, ошибка: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [Multiple exceptions: [WinError 121] Превышен таймаут семафора, [WinError 1231] Сетевая папка недоступна. За информацией о разрешении проблем в сети обратитесь к справочной системе Windows]
